/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import clases.Agente;
import clases.Arma;
import clases.Mapa;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import usoApi.BuscarApi;

/**
 *
 * @author erick
 */
public class Buscar extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    BuscarApi buscarApi;
    int numeroRecurso = 0;
    ArrayList<Object> lista;
    String objeto = null;

    public Buscar(String esJugable, String idioma, String objeto) {
        initComponents();
        this.objeto = objeto;
        buscarApi = new BuscarApi("https://valorant-api.com/v1/" + objeto + esJugable + idioma);
        lista = buscarApi.obtenerDatos("", objeto);
        if (lista.get(0) instanceof Agente) {
            Agente agente = (Agente) lista.get(0);
            cambiarRecurso(agente);
        } else if (lista.get(0) instanceof Mapa) {
            Mapa mapa = (Mapa) lista.get(0);
            cambiarRecurso(mapa);
        } else if (lista.get(0) instanceof Arma) {
            Arma arma = (Arma) lista.get(0);
            cambiarRecurso(arma);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaUUID = new javax.swing.JLabel();
        etiquetaDescripcion = new javax.swing.JLabel();
        etiquetaRol = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        buscarUUID = new javax.swing.JLabel();
        fieldBuscar = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        fieldUuid = new javax.swing.JTextField();
        fieldRol = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDescripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setToolTipText("");

        etiquetaNombre.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaNombre.setText("Nombre:");

        etiquetaUUID.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaUUID.setText("UUID:");

        etiquetaDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaDescripcion.setText("Descripción:");

        etiquetaRol.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaRol.setText("Rol:");

        botonAtras.setBackground(new java.awt.Color(255, 51, 102));
        botonAtras.setText("Atrás");
        botonAtras.setToolTipText("");
        botonAtras.setEnabled(false);
        botonAtras.setFocusPainted(false);
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botonSiguiente.setBackground(new java.awt.Color(255, 51, 102));
        botonSiguiente.setText("Siguiente");
        botonSiguiente.setFocusPainted(false);
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        buscarUUID.setForeground(new java.awt.Color(255, 255, 255));
        buscarUUID.setText("Buscar por UUID: ");

        fieldBuscar.setBackground(new java.awt.Color(51, 51, 51));
        fieldBuscar.setForeground(new java.awt.Color(255, 255, 255));

        botonBuscar.setBackground(new java.awt.Color(255, 51, 102));
        botonBuscar.setText("Buscar");
        botonBuscar.setFocusPainted(false);
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        imagen.setBackground(new java.awt.Color(51, 51, 51));
        imagen.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
        );

        fieldNombre.setEditable(false);
        fieldNombre.setBackground(new java.awt.Color(51, 51, 51));
        fieldNombre.setForeground(new java.awt.Color(255, 255, 255));

        fieldUuid.setEditable(false);
        fieldUuid.setBackground(new java.awt.Color(51, 51, 51));
        fieldUuid.setForeground(new java.awt.Color(255, 255, 255));

        fieldRol.setEditable(false);
        fieldRol.setBackground(new java.awt.Color(51, 51, 51));
        fieldRol.setForeground(new java.awt.Color(255, 255, 255));

        areaDescripcion.setEditable(false);
        areaDescripcion.setBackground(new java.awt.Color(51, 51, 51));
        areaDescripcion.setColumns(20);
        areaDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        areaDescripcion.setLineWrap(true);
        areaDescripcion.setRows(5);
        areaDescripcion.setFocusable(false);
        jScrollPane1.setViewportView(areaDescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(buscarUUID, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(fieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(etiquetaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(etiquetaUUID, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fieldUuid, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(etiquetaRol, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fieldRol, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(etiquetaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarUUID)
                    .addComponent(fieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaNombre)
                            .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaUUID)
                            .addComponent(fieldUuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaRol)
                            .addComponent(fieldRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(etiquetaDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAtras)
                    .addComponent(botonSiguiente))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        if (numeroRecurso == lista.size() - 2) {
            botonSiguiente.setEnabled(false);
        }
        botonAtras.setEnabled(true);
        numeroRecurso++;
        Object agente = lista.get(numeroRecurso);
        cambiarRecurso(agente);
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        try {
            buscarApi = new BuscarApi("https://valorant-api.com/v1/agents/"
                    + fieldBuscar.getText() + "?language=es-ES");
            ArrayList<Object> lista = buscarApi.obtenerDatos("Unico", objeto);
            Object agente = lista.get(0);
            cambiarRecurso(agente);
            botonAtras.setEnabled(false);
            botonSiguiente.setEnabled(false);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        if (numeroRecurso <= 1) {
            botonAtras.setEnabled(false);
        }
        botonSiguiente.setEnabled(true);
        numeroRecurso--;
        Object agente = lista.get(numeroRecurso);
        cambiarRecurso(agente);
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void cambiarRecurso(Object recurso) {
        String nombre = "";
        String uuid = "";
        String rol = "";
        String descripcion = "";
        String imagenString = "";
        if (recurso instanceof Agente) {
            nombre = ((Agente) recurso).getNombre();
            uuid = ((Agente) recurso).getUuid();
            rol = ((Agente) recurso).getRol();
            descripcion = ((Agente) recurso).getDescripcion();
            imagenString = ((Agente) recurso).getImagen();
        } else if (recurso instanceof Mapa) {
            nombre = ((Mapa) recurso).getNombre();
            uuid = ((Mapa) recurso).getUuid();
            descripcion = ((Mapa) recurso).getDescripcion();
            imagenString = ((Mapa) recurso).getImagen();
        } else if (recurso instanceof Arma) {
            nombre = ((Arma) recurso).getNombre();
            uuid = ((Arma) recurso).getUuid();
            imagenString = ((Arma) recurso).getImagen();
        }
        fieldNombre.setText(nombre);
        fieldUuid.setText(uuid);
        fieldRol.setText(rol);
        areaDescripcion.setText(descripcion);
        int ancho = 210;
        int alto = 210;
        ImageIcon icono = redimensionarImagen(imagenString, ancho, alto);
        imagen.setIcon(icono);
    }

    //Metodo para redimensionarImagen
    public ImageIcon redimensionarImagen(String urlImagen, int ancho, int alto) {
        try {
            BufferedImage imagenOriginal = ImageIO.read(new URI(urlImagen).toURL());
            Image imagenRedimensionada = imagenOriginal.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
            ImageIcon iconoRedimensionado = new ImageIcon(imagenRedimensionada);
            return iconoRedimensionado;
        } catch (IOException e) {
            return null;
        } catch (URISyntaxException ex) {
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDescripcion;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JLabel buscarUUID;
    private javax.swing.JLabel etiquetaDescripcion;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaRol;
    private javax.swing.JLabel etiquetaUUID;
    private javax.swing.JTextField fieldBuscar;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldRol;
    private javax.swing.JTextField fieldUuid;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
